### ISSUE TITLE
Extending the eventhtml

### ISSUE THREAD

**Issue by DusanV** [bradoyler/GoogleCalReader-jquery-plugin#3]
Sometimes it is useful to hide some elements or design them in some other way. So perhaps extending the code like this:

var eventhtml = '<div id="eventtitle">' + eventTitle + '</div> <div class="eventtiming">' + dayname + ' ' + monthname + ' ' + date + ', ' + time + '</div><div class="eventplace">' + eventWhere + '</div><div class="eventdesc">' + eventContent + '</div>';

? That's at least how I did it for a custom project.

**Comment by bradoyler** [comment]
thx for the tip
