### ISSUE TITLE
Display event time

### ISSUE THREAD

**Issue by marsvieyra** [bradoyler/GoogleCalReader-jquery-plugin#8]
Hey :) How can I make the event time visible? It would be really helpful :)

Thanks so much for the work you've put in this!

**Comment by bradoyler** [comment]
Oh, try setting `dateFormat:'LongDate+ShortTime'`

```js
$('#eventlist').gCalReader({
 calendarId:'your_calendar@group.v.calendar.google.com',   
 apiKey:'your_public_api_key',
 dateFormat:'LongDate+ShortTime'
});

**Comment by marsvieyra** [comment]
Thanks so much! That did it :)

*Mars.*
